project:
  type: website
  output-dir: docs

website:
  title: "Sahil Bhattacharya"
  favicon: images/favicon.png
  page-footer:
    left: "© 2025 Sahil Ashish Bhattacharya"
    center: "MSc Business Analytics · Dublin City University"
    right:
      - icon: github
        href: https://github.com/Saahil0206
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/sahil-bhattacharya-257924228
        target: _blank
  navbar:
    title: "Sahil Bhattacharya"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects/index.qmd
        text: Portfolio
      - href: skills.qmd
        text: Skills
      - href: media.qmd
        text: Media
      - href: blogs.qmd
        text: Blogs
      - href: contact.qmd
        text: Contact Details
    right:
      - href: cv/sahil-bhattacharya-cv.pdf
        text: CV
        target: _blank

format:
  html:
    theme: [litera, styles.scss]
    toc: false
    page-layout: full
    include-after-body:
      - animation.js
